### PR TITLE
add MIT license

### LINKED ISSUE #6: License?
First, thanks a lot for putting these bootstrap projects out there!

I was wondering what the license for this code is, there seems to be none specified. It would be nice if you specify one so that there is no uncertainty when using this repository.

### PR DESCRIPTION
**Pull request by holsky**
@mrksdck please have a look

closes #6

### CODE REVIEW

**Comment by mrksdck** [comment]
Will do till thursday evening, currently traveling.

Am 21. Januar 2018 22:07:55 MEZ schrieb Holger Schmeisky <notifications@github.com>:
>@mrksdck please have a look
>
>closes #6 
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/swkBerlin/kata-bootstraps/pull/23
>
>-- Commit Summary --
>
>  * add MIT license
>
>-- File Changes --
>
>    A LICENSE (21)
>
>-- Patch Links --
>
>https://github.com/swkBerlin/kata-bootstraps/pull/23.patch
>https://github.com/swkBerlin/kata-bootstraps/pull/23.diff
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/swkBerlin/kata-bootstraps/pull/23

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mrksdck** [comment]
Got sick last week, will check asap

Am 22. Januar 2018 09:48:37 MEZ schrieb Markus Decke <markus.decke@mailbox.org>:
>Will do till thursday evening, currently traveling.
>
>Am 21. Januar 2018 22:07:55 MEZ schrieb Holger Schmeisky
><notifications@github.com>:
>>@mrksdck please have a look
>>
>>closes #6 
>>You can view, comment on, or merge this pull request online at:
>>
>>  https://github.com/swkBerlin/kata-bootstraps/pull/23
>>
>>-- Commit Summary --
>>
>>  * add MIT license
>>
>>-- File Changes --
>>
>>    A LICENSE (21)
>>
>>-- Patch Links --
>>
>>https://github.com/swkBerlin/kata-bootstraps/pull/23.patch
>>https://github.com/swkBerlin/kata-bootstraps/pull/23.diff
>>
>>-- 
>>You are receiving this because you were mentioned.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/swkBerlin/kata-bootstraps/pull/23
>
>-- 
>Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail
>gesendet.

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by dcarral** [comment]
@holsky @mrksdck Thank you very much for creating this PR. Perhaps we might wanna consider replacing the “year” and “full name” placeholders with concrete values?

**Comment by mrksdck** [comment]
finally did it, thanks for the review @dcarral

**Comment by holsky** [comment]
nice catch @dcarral :)

**Pull request merged**
