### PR TITLE
Added C++ bootstrap project

### PR DESCRIPTION
**Pull request by madduci**
Bootstrap C++ project based on CMake and doctest for cross platform development (Compatible with gcc, clang, mingw and Visual Studio)

### CODE REVIEW

**Comment by ikusalic** [comment]
Thanks for the contribution Michele, finally a C++ one. :))

It doesn't really work on my machine.
When I run make:

~~~
[ 25%] Building CXX object CMakeFiles/game_of_life.dir/src/game_of_life.cpp.o
make test
/Users/kusalic/other/source/project-bootstraps/cpp/src/game_of_life.cpp:7:24: warning: defaulted function definitions are a C++11 extension
      [-Wc++11-extensions]
        GameOfLife() = default;
                       ^
/Users/kusalic/other/source/project-bootstraps/cpp/src/game_of_life.cpp:14:20: error: expected ';' at end of declaration
    GameOfLife game{};
                   ^
                   ;
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/game_of_life.dir/src/game_of_life.cpp.o] Error 1
make[1]: *** [CMakeFiles/game_of_life.dir/all] Error 2
make: *** [all] Error 2
~~~

Can you also only have one example? This repo is used for all kinds of katas, not just game of life, so no need to have something GoL specific here.

Just so you have more context, I've also tried just removing game of life part, but I still get errors:

~~~
Scanning dependencies of target hello_world
[ 50%] Building CXX object CMakeFiles/hello_world.dir/src/hello_world.cpp.o
/Users/kusalic/other/source/project-bootstraps/cpp/src/hello_world.cpp:6:5: error: unknown type name 'constexpr'
    constexpr auto message{"Hello World"};
    ^
/Users/kusalic/other/source/project-bootstraps/cpp/src/hello_world.cpp:6:15: error: expected unqualified-id
    constexpr auto message{"Hello World"};
              ^
/Users/kusalic/other/source/project-bootstraps/cpp/src/hello_world.cpp:7:11: error: use of undeclared identifier 'message'
    CHECK(message == "Hello World");
          ^
/Users/kusalic/other/source/project-bootstraps/cpp/include/doctest.h:825:50: note: expanded from macro 'DOCTEST_CHECK'
#define DOCTEST_CHECK(expr) DOCTEST_ASSERT_PROXY(expr, "CHECK", ((void)0))
                                                 ^
/Users/kusalic/other/source/project-bootstraps/cpp/include/doctest.h:814:50: note: expanded from macro 'DOCTEST_ASSERT_PROXY'
                        DOCTEST_ASSERT_IMPLEMENT(expr, assert_name, false_invert_op)               \
                                                 ^
/Users/kusalic/other/source/project-bootstraps/cpp/include/doctest.h:794:58: note: expanded from macro 'DOCTEST_ASSERT_IMPLEMENT'
        res = doctest::detail::ExpressionDecomposer() << expr;                                     \
                                                         ^
3 errors generated.
make[2]: *** [CMakeFiles/hello_world.dir/src/hello_world.cpp.o] Error 1
make[1]: *** [CMakeFiles/hello_world.dir/all] Error 2
make: *** [all] Error 2
~~~

It's probably something trivial that needs to be added to Readme, but I haven't been in C++ world for 12 years. :)

Thank you & cheers

**Comment by madduci** [comment]
your compiler seems to not support C++11 properly, it complains with -Wc++11-extensions.
I will refactor to have only one example :)

**Comment by madduci** [comment]
Ok I've updated the project with a generic kata.cpp file and added explicit compiler flag -std=c++11 to enable the standard on old versions of compilers (e.g. gcc prior to version 5)

**Comment by madduci** [comment]
Ok I've updated the project with a generic kata.cpp file and added explicit compiler flag -std=c++11 to enable the standard on old versions of compilers (e.g. gcc prior to version 5). 
Doctest itself uses some new C++ (14) features and it complains when they are not found.

**Comment by ikusalic** [comment]
Thank you :)

**Comment by madduci** [comment]
you're welcome ;-)

**Pull request merged**
