### PR TITLE
add ts ci

### PR DESCRIPTION
**Pull request by mklose**
- adding CI for typescript

### CODE REVIEW

**Comment by dbartholomae** [comment]
Won't this fail all the time since one test is always failing?

**Comment by mklose** [comment]
> Won't this fail all the time since one test is always failing?

it did not fail https://github.com/swkBerlin/kata-bootstraps/runs/1380513318 that's because there is no failing test for  ts/typescript-jest ...

**Comment by dbartholomae** [comment]
Good point. I can fix that by adapting tests to the default 42 example. But maybe asked another way: What's the goal of the CI? I saw that there are some ideas around CI for this repo, but I'm not sure I have the full picture yet :)

**Comment by mklose** [comment]
I've notice in the past that some setups have been broken. That's why I'd like to make sure they actually work also with different versions of languages and operating systems

**Pull request merged**
