### PR TITLE
Add ReScript Starter

### PR DESCRIPTION
**Pull request by marcoemrich**
adds a starter for the new ReScript language (https://rescript-lang.org/) using Jest as testing framework

### CODE REVIEW

**Comment by dbartholomae** [comment]
Thanks! What should the Win+Shift+B command do mentioned in the README? It doesn't work for me.

**Comment by dbartholomae** [comment]
@marcoemrich it also seems that there are other people working on this branch as well, there is a python related commit on this branch now :)

**Comment by marcoemrich** [comment]
@dbartholomae the "Win+Shift+B" was in the ReScript-Readme from the application generator - I just did not delete it.

I wasn't aware that I'm not alone on the branch :) - I added the ReScript example to the Vienna fork of the repo first, because I joined their coderetreat. And then I just did a PR to upstream it to the original Berlin Repo - looks like other updates to the Vienna Repo end up in the same PR. weird? Any idea how to clean this up?

**Comment by dbartholomae** [comment]
I would suggest setting up a new branch for ReScript (based on `master`), dropping the superfluous commit and either removing the shortcut or researching it to add more info (I would assume it pertains to a setting in a VSCode settings JSON file that is missing).

**Comment by mklose** [comment]
Hallo @marcoemrich ❤️ for contributing !

Would you be keen to [setup CI](https://github.com/swkBerlin/kata-bootstraps/tree/master/.github/workflows) (see [README](https://github.com/swkBerlin/kata-bootstraps/blob/master/README.md)) for it too?

**Comment by marcoemrich** [comment]
made a new clean PR in #84

**Comment by marcoemrich** [comment]
sure - will see if I can get this up and running

**Comment by marcoemrich** [comment]
this PR is obsolete because of #84 and #85

**Pull request closed without merging**
