### PR TITLE
Adding clojure skeleton

### PR DESCRIPTION
**Pull request by MiyamotoAkira**
Initial skeleton for Clojure

### CODE REVIEW

**Comment by holsky** [comment]
hey thanks for your effort! could you dockerize this as well, like for rust? makes it a little easier :)

**Comment by MiyamotoAkira** [comment]
Sure, will do during the week

**Comment by MiyamotoAkira** [comment]
Added the dockerization following the rust example

**Comment by mrksdck** [comment]
Tested it with test.sh and works.

**Comment by mrksdck** [comment]
@MiyamotoAkira Thank you for your work!

**Pull request merged**
