### PR TITLE
add property based testing example with TypeScript

### PR DESCRIPTION
**Pull request by dbartholomae**
This adds a repo with property based testing based on https://github.com/dubzzz/fast-check
I've hacked this together during a coding kata, so it might need a bit of work.

### CODE REVIEW

**Comment by dbartholomae** [comment]
It did work out well for four participants.

**Comment by mklose** [comment]
@dbartholomae it would be great to have an example of a property based test in the pull request

**Comment by dbartholomae** [comment]
The first test uses property based testing. I can rewrite the tests though in the way that makes most sense for the overall repo, e. g. with the prime factor example. Wasn't sure though if this logger example is the default for the repo and therefore didn't change anything yet.

**Comment by dbartholomae** [comment]
Any news? :)

**Pull request merged**
