### PR TITLE
Adding the skeleton for F# on dotnet

### PR DESCRIPTION
**Pull request by MiyamotoAkira**
Initial stab  at the skeleton

### CODE REVIEW

**Comment by holsky** [comment]
thanks a lot and same comment as your other PR: is it feasible to dockerize this?

**Comment by MiyamotoAkira** [comment]
As well, during the week I will setup

**Comment by holsky** [comment]
Hey Miyamoto, are you still working on the dockerization? if you do not find the time I will just merge it as it is :)

**Comment by MiyamotoAkira** [comment]
Hello,

I must say I completely forgot about. I do want to finish it myself,so I
have put a reminder to tackle it this week.

Regards,
Jorge Gueorguiev Garcia

**Comment by MiyamotoAkira** [comment]
Added the dockerization following the rust example

**Comment by mrksdck** [comment]
Tested docker way with test.sh and worked.
Thanks @MiyamotoAkira for your work!

**Pull request merged**
